// Example: Validate a Primo CMS page against a JSON AST exported by zod-codepen.
//
// This demonstrates the full workflow:
// 1. Load a JSON AST file (generated by @zod-codepen/vite-plugin)
// 2. Validate Go data against it
// 3. Inspect validation errors
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/CornWorld/zod-codepen/pkgs/go"
)

func main() {
	// Load the JSON AST document exported by the TS side.
	data, err := os.ReadFile("schemas.json")
	if err != nil {
		fmt.Printf("Error reading schemas.json: %v\n", err)
		fmt.Println("Run from the examples/primo directory.")
		os.Exit(1)
	}

	doc, err := zodval.ParseDocument(data)
	if err != nil {
		fmt.Printf("Error parsing document: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Loaded AST document version %d with %d schemas\n\n", doc.Version, len(doc.Schemas))

	// --- Validate a valid Page ---
	validPage := map[string]any{
		"id":          "page-001",
		"title":       "Getting Started",
		"slug":        "getting-started",
		"status":      "published",
		"views":       float64(42),
		"publishedAt": "2026-01-15T10:30:00Z",
	}

	fmt.Println("=== Validating a valid Page ===")
	result := zodval.ValidateSchema(doc, "Page", validPage)
	if result.IsValid() {
		fmt.Println("✓ Page is valid")
	} else {
		fmt.Println("✗ Page validation errors:")
		for _, e := range result.Errors {
			fmt.Printf("  [%s] %s: %s\n", e.Code, e.FormatPath(), e.Message)
		}
	}

	// --- Validate an invalid Page ---
	invalidPage := map[string]any{
		"id":     123,            // wrong type: number instead of string
		"title":  "",             // violates min(1)
		"slug":   "INVALID SLUG", // violates regex
		"status": "deleted",      // not in enum
		"views":  float64(-5),    // violates nonnegative
	}

	fmt.Println("\n=== Validating an invalid Page ===")
	result = zodval.ValidateSchema(doc, "Page", invalidPage)
	if result.IsValid() {
		fmt.Println("✓ Page is valid (unexpected)")
	} else {
		fmt.Printf("✗ Page has %d validation error(s):\n", len(result.Errors))
		for _, e := range result.Errors {
			fmt.Printf("  [%s] %s: %s\n", e.Code, e.FormatPath(), e.Message)
		}
	}

	// --- Validate a discriminated union (Block) ---
	textBlock := map[string]any{
		"type": "text",
		"body": "Hello, world!",
	}

	fmt.Println("\n=== Validating a Block (discriminated union) ===")
	result = zodval.ValidateSchema(doc, "Block", textBlock)
	if result.IsValid() {
		fmt.Println("✓ Text block is valid")
	} else {
		fmt.Println("✗ Block validation errors:")
		for _, e := range result.Errors {
			fmt.Printf("  [%s] %s: %s\n", e.Code, e.FormatPath(), e.Message)
		}
	}

	// --- Validate TagList (array with nonempty constraint) ---
	fmt.Println("\n=== Validating TagList (nonempty array) ===")
	result = zodval.ValidateSchema(doc, "TagList", []any{"go", "zod", "validation"})
	if result.IsValid() {
		fmt.Println("✓ TagList is valid")
	} else {
		fmt.Println("✗ TagList validation errors:")
		for _, e := range result.Errors {
			fmt.Printf("  [%s] %s: %s\n", e.Code, e.FormatPath(), e.Message)
		}
	}

	// --- Validate DefaultTheme (literal) ---
	fmt.Println("\n=== Validating DefaultTheme (literal) ===")
	result = zodval.ValidateSchema(doc, "DefaultTheme", "light")
	if result.IsValid() {
		fmt.Println("✓ 'light' is a valid DefaultTheme")
	}
	result = zodval.ValidateSchema(doc, "DefaultTheme", "dark")
	if !result.IsValid() {
		fmt.Println("✗ 'dark' is not a valid DefaultTheme (correctly rejected)")
	}

	// --- Using JSON input directly ---
	fmt.Println("\n=== Validating JSON-parsed input ===")
	jsonInput := `{"id":"page-002","title":"JSON Test","slug":"json-test","status":"draft","views":0}`
	var parsed any
	json.Unmarshal([]byte(jsonInput), &parsed)
	result = zodval.ValidateSchema(doc, "Page", parsed)
	if result.IsValid() {
		fmt.Println("✓ JSON-parsed Page is valid")
	} else {
		fmt.Println("✗ JSON Page validation errors:")
		for _, e := range result.Errors {
			fmt.Printf("  [%s] %s: %s\n", e.Code, e.FormatPath(), e.Message)
		}
	}
}
